os: Visual Studio 2015

environment:
  matrix:
    - target: x86_64-pc-windows-msvc
    - target: i686-pc-windows-msvc
    - target: x86_64-pc-windows-gnu
    - target: i686-pc-windows-gnu

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-host %target% --default-toolchain stable
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup toolchain install beta
  - rustup toolchain install nightly
  - ps: |
      Function Test() {
        echo "Testing stable"
        rustup run stable cargo test $args 2> $null
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
        echo "Testing stable --release"
        rustup run stable cargo test --release $args 2> $null
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }

        echo "Testing beta"
        rustup run beta cargo test $args 2> $null
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
        echo "Testing beta --release"
        rustup run beta cargo test --release $args 2> $null
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }

        echo "Testing nightly"
        rustup run nightly cargo test $args 2> $null
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
        echo "Testing nightly --release"
        rustup run nightly cargo test --release $args 2> $null
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
      }

build: false

test_script:
  - cargo fmt -- --check
  - cargo clippy
  - ps: Test
  - ps: Test --features large-files
  - ps: Test --no-default-features
  - ps: Test --no-default-features --features large-files
  - ps: Test --no-default-features --features fallback-buf
  - ps: Test --no-default-features --features fallback-buf,large-files
  - ps: Test --no-default-features --features fallback-bufreader
  - ps: Test --no-default-features --features fallback-bufreader,large-files